### ISSUE TITLE
Partners Filter and Sort Function

### ISSUE THREAD

**Issue by Cyapher** [Cyapher/pahinungod_forms#49]

**Comment by maikerucode** [comment]
![Image](https://github.com/Cyapher/pahinungod_forms/assets/65951580/97fea468-a115-4cef-9ad5-8ced1d36252a)

**Comment by maikerucode** [comment]
![Image](https://github.com/Cyapher/pahinungod_forms/assets/65951580/b58ef936-bde8-4b80-bcfe-4ac3df250009)
